# Generated by Django 4.0.5 on 2022-06-22 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myprofile',
            old_name='status',
            new_name='stat',
        ),
    ]
